# Generated by Django 5.2.3 on 2025-06-20 03:16

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('days_of_week', models.JSONField(default=list)),
                ('base_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_distance_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rime_multipliers', models.JSONField(default=list, help_text="JSON: [{'threshold':60, 'multiplier': 1.0}, ... ]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pricing.pricingconfig')),
            ],
        ),
    ]
