# Generated by Django 5.2.3 on 2025-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingconfig',
            old_name='rime_multipliers',
            new_name='time_multipliers',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='free_waiting_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='waiting_charge_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='waiting_charge_per_interval',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
